### ISSUE TITLE
I can not config my interceptors in application.yml

### ISSUE THREAD

**Issue by ZuiSong** [mybatis/spring-boot-starter#180] opened 2017-07-27 04:42 UTC
```
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #config-location: classpath:mybatis-conf.xml
  configuration:
    interceptors:
      - cn.mmooo.SqlExplainInterceptor
```
`
***************************
APPLICATION FAILED TO START
***************************

Description:

Binding to target org.mybatis.spring.boot.autoconfigure.MybatisProperties@545e57d7 failed:

    Property: mybatis.configuration.interceptors[0]
    Value: cn.mmooo.SqlExplainInterceptor
    Reason: Failed to convert property value of type 'java.lang.String' to required type 'org.apache.ibatis.plugin.Interceptor' for property 'configuration.interceptors[0]'; nested exception is java.lang.IllegalStateException: Cannot convert value of type 'java.lang.String' to required type 'org.apache.ibatis.plugin.Interceptor' for property 'interceptors[0]': no matching editors or conversion strategy found

Action:

Update your application's configuration
`

I can not config my interceptors in application.yml

**Comment by kazuki43zoo** [comment] 2017-07-27 05:55
In current implementation, you cannot apply custom `Interceptor` using `application.properties`(`application.yml`). 

**Note: This is a known limitation.**

Instead of it, you can apply a custom `Interceptor` using [interceptor auto-detection feature(see Detecting MyBatis components)](http://www.mybatis.org/spring-boot-starter/mybatis-spring-boot-autoconfigure/#Detecting_MyBatis_components) provided by mybatis-spring-boot-autoconfigure as follow:

```java
@Configuration
public class YourMyBatisConfiguration {
    @Bean
    SqlExplainInterceptor sqlExplainInterceptor() {
        return new SqlExplainInterceptor();
    }
}

**Comment by kazuki43zoo** [comment] 2017-08-04 18:07
@ZuiSong I've closed this issue, however you can reopen this issue always.

**Closed by kazuki43zoo** 2017-08-04 18:07 UTC

**Comment by dong6708** [comment] 2017-08-07 02:34
hello,Did you solve it

**Comment by ZuiSong** [comment] 2017-11-24 03:24
@dong6708  I solved it just like @kazuki43zoo writed. Create a bean that mybatis would auto add it to interceptors

**Comment by marvin-min** [comment] 2018-04-02 14:54
works for me .thanks.

**Comment by sp121933039** [comment] 2018-05-30 15:35
求解决方法

**Comment by cookerzhu** [comment] 2018-06-01 10:28
I've encountered this issue , Add @Bean in Spring boot Application:
@Bean
    public Interceptor getInterceptor(){
        return new PageInterceptor();
    }

**Comment by ihoment-troy** [comment] 2018-11-15 07:55
It's still not work for me, is there any wrong with my code?

`@Configuration
public class MybatisPluginsConfig {

    @Bean
    public TableSplitByModuloInterceptor TableSplitByModuloInterceptor() {
        return new TableSplitByModuloInterceptor();
    }
}`
`@Intercepts({
        @Signature(type = StatementHandler.class, method = "prepare", args = { Connection.class, Integer.class })
})
public class TableSplitByModuloInterceptor implements Interceptor {

    private static final Logger logger = LoggerFactory.getLogger();
    private static final ObjectFactory DEFAULT_OBJECT_FACTORY = new DefaultObjectFactory();
    private static final ObjectWrapperFactory DEFAULT_OBJECT_WRAPPER_FACTORY = new DefaultObjectWrapperFactory();
    private static final ReflectorFactory DEFAULT_REFLECTOR_FACTORY = new DefaultReflectorFactory();


    @Override
    public Object intercept(Invocation invocation) throws Throwable {
        StatementHandler statementHandler = (StatementHandler) invocation.getTarget();
        return invocation.proceed();

    }

    @Override
    public Object plugin(Object target) {
        if (target instanceof StatementHandler) {
            return Plugin.wrap(target, this);
        } else {
            return target;
        }
    }

    @Override
    public void setProperties(Properties properties) {

    }
`

**Comment by kazuki43zoo** [comment] 2018-11-15 15:21
@ihoment-troy Could you provide more detail information? I cannot  understand a your problem...

I expect to provide information as follows:

* small reproduce project via GtiHub
* stack trace?

And this issue was closed already. If you have a problem, please create new issue with more detail information.

Thanks.

**Comment by duochiqingcai** [comment] 2019-11-28 10:40
thanks,it works.

**Comment by SuqiangDai** [comment] 2021-07-23 00:16
using :
    interceptors:
      - com.daisq.web.interceptor.MybatisPagination
in my yml file to set configure mybatis and i got an error :
    Failed to bind properties under 'mybatis.configuration.interceptors[0]' to org.apache.ibatis.plugin.Interceptor
later i changed my yml file to :
    interceptors:
      {com.daisq.web.interceptor.MybatisPagination}
and my application start up correctly

**Comment by kk-fan** [comment] 2021-09-24 08:26
> using :
> interceptors:
> - com.daisq.web.interceptor.MybatisPagination
> in my yml file to set configure mybatis and i got an error :
> Failed to bind properties under 'mybatis.configuration.interceptors[0]' to org.apache.ibatis.plugin.Interceptor
> later i changed my yml file to :
> interceptors:
> {com.daisq.web.interceptor.MybatisPagination}
> and my application start up correctly

I tried it. Although there was no error, But the interceptor didn't work
