### ISSUE TITLE
Can not access org.mybatis.spring.SqlSessionFactoryBean

### ISSUE THREAD

**Issue by 1770132012** [mybatis/spring-boot-starter#789] opened 2023-02-07 00:36 UTC
version: `3.0.1`
`<dependency>`
`    <groupId>org.mybatis.spring.boot</groupId>`
`    <artifactId>mybatis-spring-boot-starter</artifactId>`
`    <version>3.0.1</version>`
`</dependency>`

When I execute `mvn install`, there will have an Error "`Can not access org.mybatis.spring.SqlSessionFactoryBean`"， I donot know how to resolve it?

**Comment by 1770132012** [comment] 2023-02-07 00:38
I want to rewrite Configuration, but i got this error

import org.mybatis.spring.SqlSessionFactoryBean;
import org.mybatis.spring.boot.autoconfigure.SqlSessionFactoryBeanCustomizer;

public class MybatisSqlSessionFactoryBeanCustomizer implements SqlSessionFactoryBeanCustomizer {
    @Override
    public void customize(SqlSessionFactoryBean factoryBean) {
        factoryBean.setConfiguration(new MybatisConfiguration());
    }
}

**Comment by 1770132012** [comment] 2023-02-07 00:42
When I change version to `3.0.0`, this problem can be resolved.

**Comment by sialais** [comment] 2023-03-05 09:10
I've found it's caused by this commit: [Drop EnableAutoConfiguration from spring.factories](https://github.com/mybatis/spring-boot-starter/pull/755/commits/83bbac7a09a4990607d0e86c89f5db2c13b31316) , The auto config class `MybatisAutoConfiguration` not loaded by automically.
Adding `@ImportAutoConfiguration(MybatisAutoConfiguration.class)` for temporary fix.

**Comment by kazuki43zoo** [comment] 2023-05-06 21:57
> When I change version to 3.0.0, this problem can be resolved.

Sorry late reply, probably this change is not related for resolving. Could you provide **Spring Boot** version?

**Comment by kazuki43zoo** [comment] 2023-05-31 11:25
@1770132012 
I close this issue because no reply, you can always reopen.

**Closed by kazuki43zoo** 2023-05-31 11:25 UTC
Labels: waiting-feedback
