### ISSUE TITLE
MyBatis Batch rollback

### ISSUE THREAD

**Issue by masteryourself** [mybatis/spring-boot-starter#478] opened 2020-07-22 05:59 UTC
```java
@Component
@Slf4j
public class xXXHandler {

	@Autowired
    @Qualifier("externalCodeTiDbSqlSessionFactory")
    private SqlSessionFactory externalCodeTiDbSqlSessionFactory;
	
    private void batchInsert(String externalCodeApplyId, int count, int lastIdempotent) {
        ExternalCode externalCode;
        try (SqlSession sqlSession = externalCodeTiDbSqlSessionFactory.openSession(ExecutorType.BATCH, false)) {
            ExternalCodeMapper mapper = sqlSession.getMapper(ExternalCodeMapper.class);
            for (int i = 0; i < count; i++) {
                externalCode = new ExternalCode();
                externalCode.setExternalCodeApplyId(externalCodeApplyId);
                externalCode.setIdempotent(++lastIdempotent);
                mapper.insertSelective(externalCode);
            }
            sqlSession.commit();
        } catch (Exception e) {
            // externalCodeApplyId + lastIdempotent is unique index in DB
            if (e.getMessage().contains("uk_external_code_apply_id_idempotent")) {
                log.warn("ExternalCodeAsyncHandler.insertExternalCode() , externalCodeApplyId: {}, lastIdempotent: {}", externalCodeApplyId, lastIdempotent);
            }
            // I have a question here: Will this method(rollback) work?
            sqlSession.rollback();
        }
    }

}
```

Another question: ExecutorType.BATCH is very slow, Did I use it wrong? Please help me, thank you alot.

This question: Will this method(rollback) work?
I mean, `insert external_code("xxx",1)` , `insert external_code("xxx",2)`, `insert external_code("xxx",3)`, suppose `external_code("xxx",2)`  has been exist, `external_code("xxx",1), external_code("xxx",3)` will rollback or insert?
My test is `external_code("xxx",2)` no insert, but  `external_code("xxx",1), external_code("xxx",3)` insert, If I want to rollback all, how do I do?

**Comment by harawata** [comment] 2020-07-24 02:32
Hello @masteryourself ,

Investigating a performance issue without reproducing it is quite difficult.
Can you create a small project (minimum tables, columns, objects, ...) like [these](https://github.com/harawata/mybatis-issues) so that we can reproduce the problem on our end?

**Comment by masteryourself** [comment] 2020-07-24 03:03
I agree with you, performance issue, I will provide a project.
But now I have a serious problem：
When in ExecutorType.BATCH , `insert external_code("xxx",1)` , `insert external_code("xxx",2)`, `insert external_code("xxx",3)`, suppose `external_code("xxx",2)` has been exist, `external_code("xxx",1)`, `external_code("xxx",3)` will rollback or insert?
My test is `external_code("xxx",2)` no insert, but `external_code("xxx",1)`, `external_code("xxx",3)` insert, If I want to rollback all, how do I do?

```
CREATE TABLE `external_code` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `apply_id` varchar(40) NOT NULL DEFAULT '',
  `ctime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `mtime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ,
  `idempotent` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_code_id` (`code_id`),
  KEY `ix_ctime` (`ctime`),
  KEY `ix_mtime` (`mtime`),
  UNIQUE KEY `uk_apply_id_idempotent` (`apply_id`,`idempotent`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=1;
```

**Comment by harawata** [comment] 2020-07-24 04:07
There may be some misconfiguration, but it's also difficult to pinpoint the cause without a repo.

Here is a quick demo that shows the session is rolled back on batch operation failure.
https://github.com/harawata/mybatis-issues/tree/master/gh-sbs-478

**Comment by masteryourself** [comment] 2020-08-01 05:37
hi @harawata 
Sorry to reply your message so late, I test your demo, It's ok, but your demo just in MyBatis env, When I use Spring + MyBatis, It seems in error, I have submit my pr, please check.

**Comment by harawata** [comment] 2020-08-01 15:31
Hi @masteryourself ,

Transaction handling in MyBatis-Spring (and MyBatis-Spring-Boot) is quite different because it is managed by Spring.
Please read this documentation for the basics : https://mybatis.org/spring/transactions.html

This demo uses two `@MapperScan` annotations to prepare batch-mode mappers and non-batch-mode mappers.
https://github.com/jeffgbutler/mybatis-cockroach-demo/
See the `MyBatisAccountService` for how to control batch size, return results, etc..

**Comment by masteryourself** [comment] 2020-08-01 16:57
![image](https://user-images.githubusercontent.com/31031735/89106227-a7779a80-d45a-11ea-8594-3df180b758d5.png)
I hate gradle, It will take me a lot of time to download. When I cloned project, I will do test in mysql. You can also try.

**Comment by masteryourself** [comment] 2020-08-01 17:08
@harawata 
I known transaction handling will be managed by Spring(If in Spring env or Spring Boot), but in terms of `BATCH`, I think all op in batch is in a same jdbc connection, so if it goes wrong, all data should be rollback, but now it looks problematic.
In other words, if my code in Spring env, I can't use `BATCH` ( consider all rollback ).

**Comment by harawata** [comment] 2020-08-01 17:44
There are many users who are using batch operation.
If it does not rollback on error, we would have received a lot of bug reports, don't you think?

I rewrote an old demo. The added test `SpringBootTest#demoGhSbs478` shows you the transaction is rolled back as you expect.
https://github.com/harawata/mybatis-issues/tree/gh-sbs-478/so-60993091

**Comment by masteryourself** [comment] 2020-08-02 05:27
@harawata 
Thank you, I checked my project carefully, I forgot add this parameter `rewriteBatchedStatements=true`.
Demo about session rollback in Spring env I have fix, https://github.com/harawata/mybatis-issues/tree/master/gh-sbs-478, just add parameter, then all rollback if error.
So question about `ExecutorType.BATCH` is very slow, I don't think it is a problem anymore.
Anyway, think you for your answer.

**Comment by masteryourself** [comment] 2020-08-02 05:44
By the way. Which do you think is better about `ExecutorType.BATCH` and `INSERT INTO xxx VALUES (),(),()...`. Have you ever tested?

**Comment by harawata** [comment] 2020-08-02 18:50
Hello @masteryourself ,

The latest code looks almost perfect 👍, but the transaction is still committed (you can verify it in the log) because you catch and swallow the exception in `UserService#insertBatch()`.
To rollback the transaction, an exception should be thrown (you can catch it in the caller method).

`rewriteBatchedStatements` is good for performance, but it has nothing to do with transaction handling.
It tells the driver to rewrite the batched multiple insert statements into a single multi-row insert statement.
And that is why no rows are inserted even though the transaction is not rolled back (only one INSERT statement is executed (internally) and it fails).

> Which do you think is better about ExecutorType.BATCH and INSERT INTO xxx VALUES (),(),().... 

`ExecutorType.BATCH` is much better if you insert many rows.

Closing as there is no bug. 🎉

**Closed by harawata** 2020-08-02 18:50 UTC
