### ISSUE TITLE
About the problems encountered in using declarative transactions in spring-mybatis

### ISSUE THREAD

**Issue by killersteps** [mybatis/spring-boot-starter#604] opened 2021-12-13 12:28 UTC
Hello, dear partner:
I have a problem that has bothered me recently. I want to consult here.
We all know that spring's transaction management is due to the cglib proxy problem. When methods in the same class call each other or the called method is private, the transaction will be invalid. This is a bug that is easy to appear on other orm frameworks. Such as hibernate, jpa, etc.
But the following sample code can be rolled back normally in springboot-mybatis.

this is mybatis mapper code:

```java
public interface TestMapper() {

    @Update("update table set field = '123' where id = 123)");
    int testUpdate();

}
```

this is the code of a test class, which contains a private method b, and method a is controlled by the spring transaction manager:

```java
@Service
public class testA() {

    @Autowried
    TestMapper testMapper;
    
    @Transactional(rollBackFor = Exception.class)
    public void a() {
        b();
    }
    
    private void b() {
        testMapper.testUpdate();
        int a = 1/0;
    }

}
```

When the a method of the testA class is called, the b method will be called and an exception that the divisor cannot be 0 is thrown, the strange thing was actually rolled back.
When method b belongs to a method in another class and does not use spring's declarative transaction management, the same result will be obtained.
When I debug the source code, I found that the SqlSessionUtils class handles the relevant logic. I would like to ask whether the transaction is related to the current thread in the spring-mybatis project, that is to say, all the method chains called by the same thread share a transaction?
Looking forward to the answer, thanks :）

**Comment by kazuki43zoo** [comment] 2021-12-13 13:36
Sorry, I don't know what's problem...
I think this behavior is specification of spring transaction management feature.

**Comment by killersteps** [comment] 2021-12-13 15:44
> Sorry, I don't know what's problem...
> I think this behavior is specification of spring transaction management feature.

In fact, spring's declarative transaction management is implemented based on aop technology. In this example, the method of calling method b is through the current class instance, not the proxy class, so when other orm frameworks process the same code, things will No rollback will happen, mybatis is a special case, because I think mybatis has changed the basic principle of spring declarative thing management

**Comment by kazuki43zoo** [comment] 2021-12-13 15:49
> , so when other orm frameworks process the same code, things will No rollback will happen,

This explanation is really? The Spring JDBC become same behavior? Cloud you provide a reproduce project using Spring JDBC / JPA / ...etc ?

**Comment by killersteps** [comment] 2021-12-13 15:53
> Sorry, I don't know what's problem...
> I think this behavior is specification of spring transaction management feature.

In the mybatis-spring project, for a user request, assuming that there is only one thread processing, all database operations that occur, no matter which class these operations are in, and the methods in which class, as long as the entry function is marked with spring declarative things, Rollback
In fact, this is contrary to spring's declarative transaction management, because spring declarative transaction management requires classes to be accessed through proxy classes

**Comment by killersteps** [comment] 2021-12-13 15:57
> > , so when other orm frameworks process the same code, things will No rollback will happen,
> 
> This explanation is really? The Spring JDBC become same behavior? Cloud you provide a reproduce project using Spring JDBC / JPA / ...etc ?

Yes, I use JdbcTemplate to implement the same code, things will not roll back, the most critical point is the way to access method b (not through the proxy class) and method b is private

**Comment by killersteps** [comment] 2021-12-13 16:06
> > , so when other orm frameworks process the same code, things will No rollback will happen,
> 
> This explanation is really? The Spring JDBC become same behavior? Cloud you provide a reproduce project using Spring JDBC / JPA / ...etc ?

![384F1057-0F53-475F-88E1-6191219D0307](https://user-images.githubusercontent.com/34531389/145846639-fd19c8dd-0b26-40bc-bd22-71bea0227a2e.jpeg)

**Comment by kazuki43zoo** [comment] 2021-12-13 16:30
I tried using Spring JDBC, it will be rollback. Is my sample code wrong?

Version: Spring Boot 2.6.1 and mybatis-spring-boot 2.2.0(mybatis 3.5.7 + mybatis-spring 2.0.6)

```java
package com.example.springdbaccess;

import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Select;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.ApplicationRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.jdbc.core.JdbcOperations;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@SpringBootApplication
public class SpringDbaccessApplication {

  public static void main(String[] args) {
    SpringApplication.run(SpringDbaccessApplication.class, args);
  }

  @Bean ApplicationRunner mybatis(MyBatisService service, TestMapper mapper) {
    return args -> {
      try {
        System.out.println("mybatis start..........");
        System.out.println(mapper.count());
        service.execute();
      }
      catch (Exception e) {
        System.out.println(e);
      }
      finally {
        System.out.println(mapper.count());
        System.out.println("mybatis end..........");
      }
    };
  }

  @Bean ApplicationRunner springJdbc(SpringJdbcService service, JdbcOperations operations) {
    return args -> {
      try {
        System.out.println("spring jdbc start..........");
        System.out.println(operations.queryForObject("select count(*) from test", int.class));
        service.execute();
      }
      catch (Exception e) {
        System.out.println(e);
      }
      finally {
        System.out.println(operations.queryForObject("select count(*) from test", int.class));
        System.out.println("spring jdbc end..........");
      }
    };
  }

  @Service
  public static class SpringJdbcService {

    @Autowired
    JdbcOperations operations;

    @Transactional(rollbackFor = Exception.class)
    public void execute() {
      insert();
    }

    private void insert() {
      operations.update("insert into test (name) values(?)", "Kazuki");
      int a = 1 / 0;
    }

  }

  @Service
  public static class MyBatisService {

    @Autowired
    TestMapper mapper;

    @Transactional(rollbackFor = Exception.class)
    public void execute() {
      insert();
    }

    private void insert() {
      mapper.insert("Kazuki");
      int a = 1 / 0;
    }

  }

  @Mapper
  public interface TestMapper {

    @Insert("insert into test (name) values(#{name})")
    void insert(String name);

    @Select("select count(*) from test")
    int count();

  }

}
```

---

```
2021-12-14 01:24:44.990  INFO 3986 --- [           main] c.e.s.SpringDbaccessApplication          : Starting SpringDbaccessApplication using Java 1.8.0_252 on xxx with PID 3986 (/Users/xxx/git-tmp/spring-dbaccess/target/classes started by xxx in /Users/xxx/git-tmp/spring-dbaccess)
2021-12-14 01:24:44.992 DEBUG 3986 --- [           main] c.e.s.SpringDbaccessApplication          : Running with Spring Boot v2.6.1, Spring v5.3.13
2021-12-14 01:24:44.992  INFO 3986 --- [           main] c.e.s.SpringDbaccessApplication          : No active profile set, falling back to default profiles: default
2021-12-14 01:24:45.490  INFO 3986 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2021-12-14 01:24:45.546  INFO 3986 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2021-12-14 01:24:45.645  INFO 3986 --- [           main] c.e.s.SpringDbaccessApplication          : Started SpringDbaccessApplication in 0.864 seconds (JVM running for 1.212)
mybatis start..........
2021-12-14 01:24:45.660 DEBUG 3986 --- [           main] c.e.s.S.count                            : ==>  Preparing: select count(*) from test
2021-12-14 01:24:45.675 DEBUG 3986 --- [           main] c.e.s.S.count                            : ==> Parameters: 
2021-12-14 01:24:45.688 TRACE 3986 --- [           main] c.e.s.S.count                            : <==    Columns: COUNT(*)
2021-12-14 01:24:45.688 TRACE 3986 --- [           main] c.e.s.S.count                            : <==        Row: 0
2021-12-14 01:24:45.690 DEBUG 3986 --- [           main] c.e.s.S.count                            : <==      Total: 1
0
2021-12-14 01:24:45.701 DEBUG 3986 --- [           main] c.e.s.S.insert                           : ==>  Preparing: insert into test (name) values(?)
2021-12-14 01:24:45.703 DEBUG 3986 --- [           main] c.e.s.S.insert                           : ==> Parameters: Kazuki(String)
2021-12-14 01:24:45.704 DEBUG 3986 --- [           main] c.e.s.S.insert                           : <==    Updates: 1
java.lang.ArithmeticException: / by zero
2021-12-14 01:24:45.706 DEBUG 3986 --- [           main] c.e.s.S.count                            : ==>  Preparing: select count(*) from test
2021-12-14 01:24:45.707 DEBUG 3986 --- [           main] c.e.s.S.count                            : ==> Parameters: 
2021-12-14 01:24:45.707 TRACE 3986 --- [           main] c.e.s.S.count                            : <==    Columns: COUNT(*)
2021-12-14 01:24:45.707 TRACE 3986 --- [           main] c.e.s.S.count                            : <==        Row: 0
2021-12-14 01:24:45.707 DEBUG 3986 --- [           main] c.e.s.S.count                            : <==      Total: 1
0
mybatis end..........
spring jdbc start..........
0
java.lang.ArithmeticException: / by zero
0
spring jdbc end..........
2021-12-14 01:24:45.719  INFO 3986 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2021-12-14 01:24:45.720  INFO 3986 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
```

**Comment by killersteps** [comment] 2021-12-13 16:42
> I tried using Spring JDBC, it will be rollback. Is my sample code wrong?
> 
> Version: Spring Boot 2.6.1 and mybatis-spring-boot 2.2.0(mybatis 3.5.7 + mybatis-spring 2.0.6)
> 
> ```java
> package com.example.springdbaccess;
> 
> import org.apache.ibatis.annotations.Insert;
> import org.apache.ibatis.annotations.Mapper;
> import org.apache.ibatis.annotations.Select;
> import org.springframework.beans.factory.annotation.Autowired;
> import org.springframework.boot.ApplicationRunner;
> import org.springframework.boot.SpringApplication;
> import org.springframework.boot.autoconfigure.SpringBootApplication;
> import org.springframework.context.annotation.Bean;
> import org.springframework.jdbc.core.JdbcOperations;
> import org.springframework.stereotype.Service;
> import org.springframework.transaction.annotation.Transactional;
> 
> @SpringBootApplication
> public class SpringDbaccessApplication {
> 
>   public static void main(String[] args) {
>     SpringApplication.run(SpringDbaccessApplication.class, args);
>   }
> 
>   @Bean ApplicationRunner mybatis(MyBatisService service, TestMapper mapper) {
>     return args -> {
>       try {
>         System.out.println("mybatis start..........");
>         System.out.println(mapper.count());
>         service.execute();
>       }
>       catch (Exception e) {
>         System.out.println(e);
>       }
>       finally {
>         System.out.println(mapper.count());
>         System.out.println("mybatis end..........");
>       }
>     };
>   }
> 
>   @Bean ApplicationRunner springJdbc(SpringJdbcService service, JdbcOperations operations) {
>     return args -> {
>       try {
>         System.out.println("spring jdbc start..........");
>         System.out.println(operations.queryForObject("select count(*) from test", int.class));
>         service.execute();
>       }
>       catch (Exception e) {
>         System.out.println(e);
>       }
>       finally {
>         System.out.println(operations.queryForObject("select count(*) from test", int.class));
>         System.out.println("spring jdbc end..........");
>       }
>     };
>   }
> 
>   @Service
>   public static class SpringJdbcService {
> 
>     @Autowired
>     JdbcOperations operations;
> 
>     @Transactional(rollbackFor = Exception.class)
>     public void execute() {
>       insert();
>     }
> 
>     private void insert() {
>       operations.update("insert into test (name) values(?)", "Kazuki");
>       int a = 1 / 0;
>     }
> 
>   }
> 
>   @Service
>   public static class MyBatisService {
> 
>     @Autowired
>     TestMapper mapper;
> 
>     @Transactional(rollbackFor = Exception.class)
>     public void execute() {
>       insert();
>     }
> 
>     private void insert() {
>       mapper.insert("Kazuki");
>       int a = 1 / 0;
>     }
> 
>   }
> 
>   @Mapper
>   public interface TestMapper {
> 
>     @Insert("insert into test (name) values(#{name})")
>     void insert(String name);
> 
>     @Select("select count(*) from test")
>     int count();
> 
>   }
> 
> }
> ```
> 
>  ```
> 2021-12-14 01:24:44.990  INFO 3986 --- [           main] c.e.s.SpringDbaccessApplication          : Starting SpringDbaccessApplication using Java 1.8.0_252 on xxx with PID 3986 (/Users/xxx/git-tmp/spring-dbaccess/target/classes started by xxx in /Users/xxx/git-tmp/spring-dbaccess)
> 2021-12-14 01:24:44.992 DEBUG 3986 --- [           main] c.e.s.SpringDbaccessApplication          : Running with Spring Boot v2.6.1, Spring v5.3.13
> 2021-12-14 01:24:44.992  INFO 3986 --- [           main] c.e.s.SpringDbaccessApplication          : No active profile set, falling back to default profiles: default
> 2021-12-14 01:24:45.490  INFO 3986 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
> 2021-12-14 01:24:45.546  INFO 3986 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
> 2021-12-14 01:24:45.645  INFO 3986 --- [           main] c.e.s.SpringDbaccessApplication          : Started SpringDbaccessApplication in 0.864 seconds (JVM running for 1.212)
> mybatis start..........
> 2021-12-14 01:24:45.660 DEBUG 3986 --- [           main] c.e.s.S.count                            : ==>  Preparing: select count(*) from test
> 2021-12-14 01:24:45.675 DEBUG 3986 --- [           main] c.e.s.S.count                            : ==> Parameters: 
> 2021-12-14 01:24:45.688 TRACE 3986 --- [           main] c.e.s.S.count                            : <==    Columns: COUNT(*)
> 2021-12-14 01:24:45.688 TRACE 3986 --- [           main] c.e.s.S.count                            : <==        Row: 0
> 2021-12-14 01:24:45.690 DEBUG 3986 --- [           main] c.e.s.S.count                            : <==      Total: 1
> 0
> 2021-12-14 01:24:45.701 DEBUG 3986 --- [           main] c.e.s.S.insert                           : ==>  Preparing: insert into test (name) values(?)
> 2021-12-14 01:24:45.703 DEBUG 3986 --- [           main] c.e.s.S.insert                           : ==> Parameters: Kazuki(String)
> 2021-12-14 01:24:45.704 DEBUG 3986 --- [           main] c.e.s.S.insert                           : <==    Updates: 1
> java.lang.ArithmeticException: / by zero
> 2021-12-14 01:24:45.706 DEBUG 3986 --- [           main] c.e.s.S.count                            : ==>  Preparing: select count(*) from test
> 2021-12-14 01:24:45.707 DEBUG 3986 --- [           main] c.e.s.S.count                            : ==> Parameters: 
> 2021-12-14 01:24:45.707 TRACE 3986 --- [           main] c.e.s.S.count                            : <==    Columns: COUNT(*)
> 2021-12-14 01:24:45.707 TRACE 3986 --- [           main] c.e.s.S.count                            : <==        Row: 0
> 2021-12-14 01:24:45.707 DEBUG 3986 --- [           main] c.e.s.S.count                            : <==      Total: 1
> 0
> mybatis end..........
> spring jdbc start..........
> 0
> java.lang.ArithmeticException: / by zero
> 0
> spring jdbc end..........
> 2021-12-14 01:24:45.719  INFO 3986 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
> 2021-12-14 01:24:45.720  INFO 3986 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
> ```

I'm very sorry that my code did not take home in the studio. Tomorrow I will check the code logic or other problems caused by other reasons. Thank you for your valuable code and reply.

**Comment by kazuki43zoo** [comment] 2021-12-13 17:04
I've tried using JPA(Spring Data JPA with Hibernate ORM), it rollback in this case!!

**Comment by kazuki43zoo** [comment] 2021-12-13 17:06
> Tomorrow I will check the code logic or other problems caused by other reasons.

Ok.

**Comment by killersteps** [comment] 2021-12-14 02:23
> > Tomorrow I will check the code logic or other problems caused by other reasons.
> 
> Ok.

Sorry, the following paragraph from the official spring document has caused me a deviation in understanding:

https://docs.spring.io/spring-framework/docs/current/reference/html/data-access.html#spring-data-tier
![image](https://user-images.githubusercontent.com/34531389/145920978-89908ec6-af64-43cb-9833-666de792ca3d.png)

In fact, the declarative transaction will fail only when the code becomes as follows, because as stated in the spring official website document, "self invocation" appears, and the calling method a itself has passed through the proxy

@Service
public class testA() {

    @Autowried
    TestMapper testMapper;
    
    public void  a() {
        b();
    }
    
    @Transactional(rollBackFor = Exception.class)
    private void  b() {
        testMapper.testUpdate();
        int a = 1/0;
  }

}

Finally, thank you again for your reply and wish you all the best :)

**Comment by kazuki43zoo** [comment] 2021-12-14 03:41
Could you close this issue? In above case(processing under no transaction control), a result depends on auto commit mode on JDBC driver or ORM implementation. Please specify a `@Transactionl` on public method (e.g. `a()` method)!!

**Comment by killersteps** [comment] 2021-12-14 03:45
I understand. thank u

**Comment by killersteps** [comment] 2021-12-14 03:45
> Could you close this issue? In above case(processing under no transaction control), a result depends on auto commit mode on JDBC driver or library implementation. Please specify a `@Transactionl` on public method (e.g. `a()` method)!!

I understand. thank u

**Comment by kazuki43zoo** [comment] 2021-12-16 15:50
Probable, that's because `@Transactiona` is declared in the `CrudRepository` implementation class (`SimpleJpaRepository`). If you need rollback when throws an exception on the MyBatis core component, please try to specify the `@Transactional` on your mapper interface.

**Closed** 2021-12-17 01:47 UTC
