### ISSUE TITLE
mybatis ognl threadsafe exception

### ISSUE THREAD

**Issue by wawabear2018** [mybatis/spring-boot-starter#277] opened 2018-11-05 03:01 UTC
In my  application on production environment, the following exception was triggered at some special cases:
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.builder.BuilderException: Error evaluating expression ""

and I don't know what is the reason for that?  could anyone help me to find the reason and how to solve this problem?

**Comment by wawabear2018** [comment] 2018-11-05 03:02
my application using spring boot 1.5.13 and mybatis-3.4.0

**Comment by harawata** [comment] 2018-11-06 18:52
Hi @wawabear2018 ,
Please post the entire stack trace.
The message part by itself is not helpful very much.

**Comment by wawabear2018** [comment] 2018-11-07 02:47
Caused by: org.apache.ibatis.builder.BuilderException: Error evaluating expression 'item.itemCode != null'. Cause: org.apache.ibatis.ognl.NoSuchPropertyException: com.wdk.price.dal.domain.dataobject.HomsInPriceItemDO.itemCode
	at org.apache.ibatis.scripting.xmltags.OgnlCache.getValue(OgnlCache.java:46)
	at org.apache.ibatis.scripting.xmltags.ExpressionEvaluator.evaluateBoolean(ExpressionEvaluator.java:32)
	at org.apache.ibatis.scripting.xmltags.IfSqlNode.apply(IfSqlNode.java:34)
	at org.apache.ibatis.scripting.xmltags.MixedSqlNode.apply(MixedSqlNode.java:33)
	at org.apache.ibatis.scripting.xmltags.TrimSqlNode.apply(TrimSqlNode.java:55)
	at org.apache.ibatis.scripting.xmltags.MixedSqlNode.apply(MixedSqlNode.java:33)
	at org.apache.ibatis.scripting.xmltags.ForEachSqlNode.apply(ForEachSqlNode.java:82)
	at org.apache.ibatis.scripting.xmltags.MixedSqlNode.apply(MixedSqlNode.java:33)
	at org.apache.ibatis.scripting.xmltags.DynamicSqlSource.getBoundSql(DynamicSqlSource.java:41)
	at org.apache.ibatis.mapping.MappedStatement.getBoundSql(MappedStatement.java:292)
	at org.apache.ibatis.executor.statement.BaseStatementHandler.<init>(BaseStatementHandler.java:64)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.<init>(PreparedStatementHandler.java:40)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.<init>(RoutingStatementHandler.java:46)
	at org.apache.ibatis.session.Configuration.newStatementHandler(Configuration.java:523)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:48)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:198)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

**Comment by wawabear2018** [comment] 2018-11-07 02:48
item.itemCode is truely existed

**Comment by harawata** [comment] 2018-11-07 03:14
The latter half of the stack trace seems to be missing, but it probably is https://github.com/mybatis/mybatis-3/issues/623 .

In summary, the recommended solution is to use MyBatis 3.4.2+ (3.4.6 if possible) and Java 1.8.0_25+.
If that's not an option, there is a workaround using a custom [interceptor](https://github.com/mybatis/mybatis-3/issues/623#issuecomment-273977435).

**Comment by kazuki43zoo** [comment] 2019-01-07 17:51
@wawabear2018 Could you provide a feedback?

**Comment by kazuki43zoo** [comment] 2019-02-05 00:07
@wawabear2018 
I've closed this because root cause not belong this project and no reply from you.
If you cannot resolve this issue using the latest MyBatis version(3.5.0), please create a new issue in the [MyBatis core module](https://github.com/mybatis/mybatis-3).

Thanks.

**Closed by kazuki43zoo** 2019-02-05 00:07 UTC
Labels: waiting-feedback
