### ISSUE TITLE
Resultmap cannot accept property values in the super class

### ISSUE THREAD

**Issue by xaidanwang** [mybatis/spring-boot-starter#281] opened 2018-12-13 10:07 UTC
use mybatis-spring-boot-starter:1.3.2 spring-boot-starter-parent: 2.0.7
and I have tow class
super class:
```java
@Data
@ApiModel(value = "BaseTaskInfo",description = "")
public class BaseTaskInfo implements Serializable{

    protected Integer threshold;

    protected Boolean ispopup;

    protected Quality quality;

    protected Boolean alarmed;
}
```
sub class:

```java
@Data
public class DispatchingTaskDTO extends BaseTaskInfo {

    private List<ChannelDTO> channelDTOS;

    private List<FaceLibDTO> faceLibDTOS;

}
```
mapper.xml

```xml
  <resultMap id="BaseTaskInfoMap" type="com.gato.yun.mppr.face.model.api.bean.BaseTaskInfo">
    <result column="threshold" jdbcType="INTEGER" property="threshold" />
    <result column="ispopup" jdbcType="BIT" property="ispopup" />
    <result column="alarmed" jdbcType="INTEGER" property="alarmed" />
    <result column="quality" jdbcType="LONGVARCHAR" property="quality" typeHandler= "com.gato.yun.mppr.face.model.service.utils.ObjectTypeHandler" javaType="com.gato.yun.mppr.face.model.api.bean.Quality"/>
  </resultMap>

  <resultMap id="DispatchingTaskDTOMap" type="com.gato.yun.mppr.face.model.api.response.DispatchingTaskDTO" extends="BaseTaskInfoMap">
    <collection property="channelDTOS" ofType="com.gato.yun.mppr.face.model.api.bean.ChannelDTO">
      <result column="channeluuid" jdbcType="VARCHAR" property="channeluuid" />
      <result column="channeltype" jdbcType="VARCHAR" property="channeltype" />
    </collection>
    <collection property="faceLibDTOS" ofType="com.gato.yun.mppr.face.model.api.bean.FaceLibDTO">
      <result column="libraryuuid" jdbcType="VARCHAR" property="libraryuuid" />
    </collection>
  </resultMap>

  <select id="getDispatchingTaskDTOList" resultMap="DispatchingTaskDTOMap" >
    SELECT t.threshold,t.ispopup,t.alarmed,t.quality,tl.libraryuuid,td.channeluuid,td.channeltye FROM
    (SELECT taskuuid,threshold,ispopup,alarmed,quality FROM t_vss_face_dispatching_task WHERE enabled = TRUE and deleted = FALSE ) t
      LEFT JOIN t_vss_face_dispatching_library_rl tl ON t.taskuuid = tl.taskuuid
      LEFT JOIN t_vss_face_dispatching_device_rl td ON t.taskuuid =td.taskuuid
  </select>
```

But when I execute a select statement, resultmap cannot receive properties from the super class: threshold, ispopup, alarmed, quality

Can you solve this problem for me?
sql select result is:
DispatchingTaskDTO(channelDTOS=[ChannelDTO(channelName=null), ChannelDTO(channelName=null)], faceLibDTOS=[FaceLibDTO(libraryuuid=qwertyuiopdfghjkl, libraryname=null), FaceLibDTO(libraryuuid=fasdfasodfjoiwep, libraryname=null)])

**Comment by kazuki43zoo** [comment] 2018-12-13 13:12
@xaidanwang 

I cannot reproduce this behavior. 
Could you provide a reproduce small project of maven or gradle project via GitHub or zip file?

**Comment by xaidanwang** [comment] 2018-12-14 02:10
I have already pushed the case to github, please download it at https://github.com/xaidanwang/wechat-server.git . All the code is in the myabtis-demo module. And I have attached the sql file, and the junit test code.

**Comment by kazuki43zoo** [comment] 2018-12-16 09:35
@xaidanwang 

I've tried your reproduce project. I think it work fine by the current version(in other words, no need doing for resolving your report). Please confirm by adding assertion using JUnit or AssertJ instead of system print out as follow:

```java
Assertions.assertThat(taskDTOList.get(0).getThreshold()).isEqualTo(80);
Assertions.assertThat(taskDTOList.get(0).getIspopup()).isEqualTo(false);
Assertions.assertThat(taskDTOList.get(0).getAlarmed()).isEqualTo(true);
Assertions.assertThat(taskDTOList.get(0).getQuality().getMode()).isNull();
Assertions.assertThat(taskDTOList.get(0).getQuality().getBlur()).isEqualTo(0.0);
Assertions.assertThat(taskDTOList.get(0).getQuality().getCompleteness()).isEqualTo(0.0);
Assertions.assertThat(taskDTOList.get(0).getQuality().getOcclusion()).isEqualTo(0.0);
Assertions.assertThat(taskDTOList.get(0).getQuality().getPitch()).isEqualTo(0.0);
Assertions.assertThat(taskDTOList.get(0).getQuality().getRoll()).isEqualTo(0.0);
Assertions.assertThat(taskDTOList.get(0).getQuality().getYaw()).isEqualTo(0.0);
Assertions.assertThat(taskDTOList.get(0).getChannelDTOS()).hasSize(2);
Assertions.assertThat(taskDTOList.get(0).getChannelDTOS().get(0).getChanneluuid()).isEqualTo("iasdhfklashjdalsdfjmkl");
Assertions.assertThat(taskDTOList.get(0).getChannelDTOS().get(0).getChanneltype()).isEqualTo("vc");
Assertions.assertThat(taskDTOList.get(0).getChannelDTOS().get(1).getChanneluuid()).isEqualTo("iqweyriqweohtoiqjwlmjv");
Assertions.assertThat(taskDTOList.get(0).getChannelDTOS().get(1).getChanneltype()).isEqualTo("vc");
Assertions.assertThat(taskDTOList.get(0).getFaceLibDTOS()).hasSize(2);
Assertions.assertThat(taskDTOList.get(0).getFaceLibDTOS().get(0).getLibraryuuid()).isEqualTo("fasdfasodfjoiwep");
Assertions.assertThat(taskDTOList.get(0).getFaceLibDTOS().get(1).getLibraryuuid()).isEqualTo("qwertyuiopdfghjkl");

Assertions.assertThat(taskDTOList.get(1).getThreshold()).isEqualTo(80);
Assertions.assertThat(taskDTOList.get(1).getIspopup()).isEqualTo(false);
Assertions.assertThat(taskDTOList.get(1).getAlarmed()).isEqualTo(true);
Assertions.assertThat(taskDTOList.get(1).getQuality().getMode()).isEqualTo("1234545");
Assertions.assertThat(taskDTOList.get(1).getQuality().getBlur()).isEqualTo(0.0);
Assertions.assertThat(taskDTOList.get(1).getQuality().getCompleteness()).isEqualTo(0.0);
Assertions.assertThat(taskDTOList.get(1).getQuality().getOcclusion()).isEqualTo(0.0);
Assertions.assertThat(taskDTOList.get(1).getQuality().getPitch()).isEqualTo(0.0);
Assertions.assertThat(taskDTOList.get(1).getQuality().getRoll()).isEqualTo(0.0);
Assertions.assertThat(taskDTOList.get(1).getQuality().getYaw()).isEqualTo(0.0);
Assertions.assertThat(taskDTOList.get(1).getChannelDTOS()).hasSize(2);
Assertions.assertThat(taskDTOList.get(1).getChannelDTOS().get(0).getChanneluuid()).isEqualTo("111111111111");
Assertions.assertThat(taskDTOList.get(1).getChannelDTOS().get(0).getChanneltype()).isNull();
Assertions.assertThat(taskDTOList.get(1).getChannelDTOS().get(1).getChanneluuid()).isEqualTo("22222222222222222");
Assertions.assertThat(taskDTOList.get(1).getChannelDTOS().get(1).getChanneltype()).isNull();
Assertions.assertThat(taskDTOList.get(1).getFaceLibDTOS()).hasSize(2);
Assertions.assertThat(taskDTOList.get(1).getFaceLibDTOS().get(0).getLibraryuuid()).isEqualTo("1111111111111111111");
Assertions.assertThat(taskDTOList.get(1).getFaceLibDTOS().get(1).getLibraryuuid()).isEqualTo("22222222222222222");
```
**NOTE 1:**
I've added the `ORDER BY` in SQL for adding assertions as above as follow:

```sql
    SELECT threshold,t.ispopup,t.alarmed,t.quality,tl.libraryuuid,td.channeluuid,td.channeltype FROM
    (SELECT keyid,taskuuid,threshold,ispopup,alarmed,quality FROM t_vss_face_dispatching_task WHERE enabled = TRUE and deleted = FALSE ) t
      LEFT JOIN t_vss_face_dispatching_library_rl tl ON t.taskuuid = tl.taskuuid
      LEFT JOIN t_vss_face_dispatching_device_rl td ON t.taskuuid =td.taskuuid
    ORDER BY t.keyid, tl.libraryuuid, td.channeluuid
```

**NOTE 2:**
If you want to contains debug information of super class using lombok feature, please add the `@ToString(callSuper = true)` on child class as follow:

```java
@ToString(callSuper = true)
@Data
public class DispatchingTaskDTO extends BaseTaskInfo {
    private List<ChannelDTO> channelDTOS;
    private List<FaceLibDTO> faceLibDTOS;
}
```

**Comment by kazuki43zoo** [comment] 2018-12-16 09:38
@xaidanwang

I've closed this issue because I think it work fine.
If there is problem, please reopen this issue.

Thanks.

**Closed by kazuki43zoo** 2018-12-16 09:38 UTC
