### ISSUE TITLE
About automatic assembly

### ISSUE THREAD

**Issue by livk-cloud** [mybatis/spring-boot-starter#715] opened 2022-09-23 04:43 UTC
SpringBoot3-M5 removes the automatic assembly of spring.factories [spring boot wiki](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0.0-M5-Release-Notes)
Is it possible to upgrade the way of automatic assembly?

**Comment by linghengqian** [comment] 2022-09-24 14:33
- Duplicate of https://github.com/mybatis/spring-boot-starter/issues/607, this issue should be closed. Available at https://github.com/mybatis/spring-boot-starter/blob/master/mybatis-spring-boot-test-autoconfigure/src/main/resources/META-INF/spring/org.mybatis.spring.boot.test.autoconfigure.AutoConfigureMybatis.imports .

**Comment by kazuki43zoo** [comment] 2022-11-25 23:11
We support on mybatis-spring-boot 3.0 (not release yet, but release it as soon as possible)

**Closed by kazuki43zoo** 2022-11-25 23:11 UTC
