### ISSUE TITLE
Get java.lang.NullPointerException when using mybatis mapper

### ISSUE THREAD

**Issue by omobh** [mybatis/spring-boot-starter#353] opened 2019-06-15 12:35 UTC
Hello,I just met a problem and cann't sovlve it.
Im using springboot with mybatis, and this is the build.gradle:
```
dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-batch'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-json'
    compile 'org.mybatis.spring.boot:mybatis-spring-boot-starter:2.0.1'
    compile 'mysql:mysql-connector-java'
    providedRuntime 'org.springframework.boot:spring-boot-starter-tomcat'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.batch:spring-batch-test'
}
```
This is the application.properties:
```
logging.file=at.log
logging.path=./
#mybatis.type-aliases-package=com.blackHole.autoTransaction.mapper
spring.datasource.url=jdbc:mysql://localhost:3306/practicingDB?useUnicode=true&characterEncoding=utf-8
spring.datasource.username=root
spring.datasource.password=root@123
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
```
and this is the main class:
```
package com.blackHole.autoTransaction;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class AutoTransactionApplication {
    public static void main(String[] args) {
        SpringApplication.run(AutoTransactionApplication.class, args);
    }
}
```
the mapper interface:
```

import com.blackHole.autoTransaction.entity.TickDataEntity;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
@Mapper
public interface TickDataMapper {
    @Select("select * from tickData")
    @Results({
            @Result(property = "id", column = "id_tickData"),
            @Result(property = "tick_time", column = "tick_time"),
            @Result(property = "tick_price", column = "tick_price")
    })
    List<TickDataEntity> getAll();
}
```
the service class:
```

@Service
public class TransactionFramework {
    Logger logger = PubUtils.getLogger();
    @Autowired
    private TickDataMapper tdmapper;
    private QuotationAccepter qa;
    public TransactionFramework() {
        logger.info("tdmapper1 is running ......" + tdmapper.toString());
        qa = new QuotationAccepter();
        qa.start();
    }
}
```
and the code above will cause a java.lang.NullPointerException when executing to the line:"logger.info("tdmapper1 is running ......" + tdmapper.toString());". 
Obviously the tdmapper is not autowired and is empty which is already added the @autowired annotation and is a instance of the TickDataMapper interface. 
I have already add the @Mapper annotation to the interface.
I just don't know how to fix it.
Thank you very much !

**Comment by kazuki43zoo** [comment] 2019-06-15 12:46
Could you provide small reproduce project via GitHub(or attached file)?

**Comment by omobh** [comment] 2019-06-15 13:07
Thank you!
I just upload the project and this is the address:
https://github.com/omobh/autoTransactionSample.git
and this is the error log
at.log

**Comment by kazuki43zoo** [comment] 2019-06-15 13:47
```java
@Service
public class TransactionFramework {
    Logger logger = PubUtils.getLogger();

    private QuotationAccepter qa;

    public TransactionFramework() {

        qa = new QuotationAccepter(); // Bad code 
        qa.start();
    }

}
```

In this case, you should be inject the `QuotationAccepter` using constructor injection as follow:

```java
@Service
public class TransactionFramework {

    public TransactionFramework(QuotationAccepter qa) {
        qa.start();
    }

}
```

**Comment by kazuki43zoo** [comment] 2019-06-15 13:49
I've closed this issue because this issue does not related the `mybatis` and `mybatis-spring-boot`.

**Closed by kazuki43zoo** 2019-06-15 13:49 UTC
Labels: waiting-feedback

**Comment by omobh** [comment] 2019-06-15 14:03
It works! Thank you very much!!
But I just don't know why that code cause the problem......

**Comment by kazuki43zoo** [comment] 2019-06-15 14:25
> But I just don't know why that code cause the problem......

If you create a new instance(`new QuotationAccepter()`) in your application code(= not use the Java Config), it cannot manage the Spring DI container. Therefore a mapper instance does not inject to the `QuotationAccepter`. This problem can fix to use the instance that scanned by component-scan feature provided by Spring DI container.

There is possible that you don't understand about Spring's DI container and injection. I propose to learn the Spring DI container and about injection again.

**Comment by omobh** [comment] 2019-06-15 14:35
Got it!
You are right . Im new to spring...
Thanks again and good luck.
