### ISSUE TITLE
Mybatis spring-boot 2.4.0 mapper not injected

### ISSUE THREAD

**Issue by ghost** [mybatis/spring-boot-starter#540] opened 2021-03-08 15:57 UTC

**Comment by kazuki43zoo** [comment] 2021-03-08 18:54
Hi @sai983-app , 
I've tried your sample application. But it cannot reproduce by another error... 
I've modified your application and investigated it, Probably your custom marker annotation(`@SpringDataSource`) isn't correct.
Please it modify to as follow:

```java
@Retention(RetentionPolicy.RUNTIME) // Add this line
public @interface SpringDataSource {
    // intentionally empty
}
```

I think your sample application will not work at mybatis-spring-boot-starter 1.3.2. Did it really work in 1.3.2?

P.S.
We glad that submit the reproduction project (sample project) in a reproducible state without modification. If it's difficult, please write a repro procedures in issue.

**Comment by kazuki43zoo** [comment] 2021-05-05 22:32
Close this issue because no reply.

**Closed by kazuki43zoo** 2021-05-05 22:32 UTC
