### ISSUE TITLE
Property 'mapperLocations' was not specified or no matching resources found

### ISSUE THREAD

**Issue by raf66** [mybatis/spring-boot-starter#107] opened 2016-10-19 19:09 UTC
In my application.properties file, the only mybatis entry I have is:

   mybatis.mapper-locations=classpath_:mapper/_Mapper.xml

The actual XML files are in:
   src/main/resources/mappers/
       |-> UserMapper.xml

My Mapper interfaces are loaded using the @Mapper annotation.

I am using 1.1.1 of mybatis-spring-boot-starter

Here's the start-up log:

Searching for mappers annotated with @Mapper'
Using auto-configuration base package 'com.sample.'
Identified candidate component class: file .../db/mappers/UserMapper.class
Creating MapperFactoryBean with name 'userMapper' and ...UserMapper' mapperInterface
Enabling autowire by type for MapperFactoryBean with name 'userMapper'.
Property `configuration` or 'configLocation' not specified, using default MyBatis Configuration
Property 'mapperLocations' was not specified or no matching resources found
No org.mybatis.spring.mapper.MapperFactoryBean found.

Then:

Servlet.service() for servlet [dispatcherServlet] in context with path [/v1] threw exception [Request processing failed; nested exception is org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): ....mappers.UserMapper.selectUserById] with root cause

org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): ....mappers.UserMapper.selectUserById

Any ideas?

**Comment by raf66** [comment] 2016-10-20 15:05
My (hack) workaround is to have maven copy the XML files to the package that contains my mapper Java interface files.  I added this to the pom.xml file.

<resource>
		<targetPath>com/myapp/db/mappers</targetPath>
		<directory>${basedir}/src/main/resources/mappers</directory>
		<filtering>false</filtering>
		<includes>
			<include>**/*.xml</include>
		</includes>
</resource>

**Comment by kazuki43zoo** [comment] 2016-10-20 15:09
If possible, please provide a repro project via GitHub.

**Comment by kazuki43zoo** [comment] 2016-11-17 12:33
Hi @raf66, Can you provide a repro project via GitHub ?

**Comment by ShawnyXiao** [comment] 2016-11-29 06:50
I encouter the same problem. How to provide a repro project?

**Comment by ShawnyXiao** [comment] 2016-11-29 07:11
@kazuki43zoo I created a private repository, which contains the problem project. And I add you as a collaborator. It means that maybe you could touch the problem.

**Comment by ShawnyXiao** [comment] 2016-11-29 07:32
I have found my problem, which is very confusing.
It is like...
In IDEA IntelliJ, the structure of package of "com/xxx/xxx" will be name as "com.xxx.xxx". But if you name a package as "com.xxx.xxx", it would also be display as "com.xxx.xxx", which is very confusing.
That is the real problem what I encountered, producing the same result.

**Comment by eddumelendez** [comment] 2017-03-03 16:52
@ShawnyXiao take care naming folder for mappers :) . I will close this issue because sounds like the root cause.

**Closed by eddumelendez** 2017-03-03 16:52 UTC
Labels: waiting-feedback
