### ISSUE TITLE
mybatis-spring-boot-starter support oracle?

### ISSUE THREAD

**Issue by Davaasurenx** [mybatis/spring-boot-starter#187] opened 2017-09-11 03:43 UTC
used xml mapper. Oracle db. 
not return value of column "id". return value is 1. 
when use useGeneratedKeys="true", insert is not working. 
how get id or value of last inserted data? 
<insert id="insert" parameterType="User" keyColumn="id" keyProperty="id" parameterMap="parameters" useGeneratedKeys="true">

**Comment by kazuki43zoo** [comment] 2017-09-11 15:30
Hi @Davaasurenx,

I've closed this issue because it is belonging with mybatis core.
And please post your question to [the mailing list](https://groups.google.com/forum/#!forum/mybatis-user) instead of the github issue.

Note: I suggest to provide a small reproduce project via GitHub repository.

**Closed by kazuki43zoo** 2017-09-11 15:30 UTC

**Comment by Davaasurenx** [comment] 2017-09-12 02:50
Thank You
