### ISSUE TITLE
lazyload and secend level cache throw ClassCastException

### ISSUE THREAD

**Issue by Jnoee** [mybatis/spring-boot-starter#379] opened 2019-09-03 03:26 UTC
```java
@Mapper
@CacheNamespace
public interface UserDao {
  User getByUsername(String username);
  ...
}
```
```java
public class User {
  private Organ organ; // lazy load field
}
```

UserDao.getByUsername return a proxy object.

then cache hit, throw 
java.lang.ClassCastException: x.y.z.User_$$_jvste83_2 cannot be cast to x.y.z.User

**Comment by kazuki43zoo** [comment] 2019-09-08 06:27
@Jnoee Could you provide small reproduce project via GitHub?

**Comment by kazuki43zoo** [comment] 2019-10-15 13:47
@Jnoee What status? If no reply, I will close this issue.

**Comment by kazuki43zoo** [comment] 2019-10-28 11:54
@Jnoee  Closed because no reply.

**Closed by kazuki43zoo** 2019-10-28 11:54 UTC
Labels: waiting-feedback
