### ISSUE TITLE
lazy proxy doesn't work with kotlin pojo

### ISSUE THREAD

**Issue by andreika63** [mybatis/spring-boot-starter#728] opened 2022-10-26 10:38 UTC
Hello,
Has anybody tried to use kotlin with mybatis?
Let's assume we have resultMap's  "pojo" class with lazy select associations.
if "pojo" class has written in kotlin - lazy proxy rerurns null with lazy fields,
but if "pojo" class has written in java - all works.

mybatis-spring-boot-starter 2.2.2

**Comment by jeffgbutler** [comment] 2022-10-26 12:04
@andreika63 there is a repo full of examples of MyBatis with Kotlin here: https://github.com/jeffgbutler/mybatis-kotlin-examples

Also, MyBatis Generator will generate working Kotlin code.

I don't have anything in the repo that specifically uses lazy associations, but there are examples of overcoming some other common issues with Kotlin.

**Comment by jeffgbutler** [comment] 2022-10-26 15:09
@andreika63 I'm working on this. It's weird - the Kotlin property accessor is not causing the lazy association to fire, but if I inspect the object in the IntelliJ debugger it will fire. So my test fails if I run it without a breakpoint, but if I set a breakpoint, inspect the object, then let the test continue it works. I'm working on understanding what's happening.

**Comment by andreika63** [comment] 2022-10-26 15:14
I have absolutely the same result, when debug stops at breakpoint then getters work.

**Comment by jeffgbutler** [comment] 2022-10-26 15:24
I think this is because the debugger is calling `toString` on the object which is a configured lazy load trigger method.

**Comment by jeffgbutler** [comment] 2022-10-27 18:41
@andreika63 I looked into this in more depth be stepping through the Javassist code to see what is causing this. The god news is that there is not a problem with Javassist.

The issue is that Kotlin declares classes and fields "final" by default, and Javassist will not proxy anything that is final. So the solution is to declare the classes AND fields open in the Kotlin domain objects. I've updated my example to declare the domain objects properly, and remove the now unnecessary call to `hashCode`.

You can see my new domain objects here: https://github.com/jeffgbutler/mybatis-kotlin-examples/blob/master/src/main/kotlin/example04/lazy/Example04LazyModel.kt

With declaring classes and fields "open", lazy loading works as expected.

**Comment by jeffgbutler** [comment] 2022-10-27 18:44
I'm closing this as there is an acceptable workaround and the issue is not really related to MyBatis.

**Closed by jeffgbutler** 2022-10-27 18:44 UTC

**Comment by andreika63** [comment] 2022-10-28 05:46
Thanks!
Now I know 2 things!
1. Do not trust kotlin bytecode decompiler
2. @jeffgbutler is a cool dude
