### ISSUE TITLE
Failed to map Enum type data to entity

### ISSUE THREAD

**Issue by Niuzheju** [mybatis/spring-boot-starter#539] opened 2021-03-03 09:08 UTC
在xml中执行select,一个int类型字段映射为Enum类型时,如果前一个字段为空, Enum类型的字段就会无法赋值

**Comment by harawata** [comment] 2021-03-03 19:52
Hello @Niuzheju ,

We need to reproduce the problem there is not enough information.
Please create a small portable project like [these](https://github.com/harawata/mybatis-issues) and share it on your GitHub repository.

**Comment by kazuki43zoo** [comment] 2021-05-05 22:33
Close this issue because no reply.

**Closed by kazuki43zoo** 2021-05-05 22:33 UTC
Labels: waiting-feedback
